### ISSUE TITLE
Register license of this project

### ISSUE THREAD

**Issue by Joshix-1** [tguerin/newton#14]
Call [addLicense](https://api.flutter.dev/flutter/foundation/LicenseRegistry/addLicense.html) to make it easier for projects using this to credit this library.

**Comment by tguerin** [comment]
Do you mean you would like the Newton widget to call `addLicense`? Or would you like a helper `Newton.addLicense` that would load the license file and add the collector?

For the first case, it would be weird for the widget to do that cause it should be done once and it's not impossible for an app to instantiate multiple time the widget. It would require to have a static field somewhere to remind we added the licence. I think I would prefer the second option, let the developer call Newton.addLicense() on app starts. Wdyt?

**Comment by Joshix-1** [comment]
I think libraries are supposed to do that automatically once on import

**Comment by tguerin** [comment]
Do you have libraries in mind which do that already? Feels dirty to have a kind of static code called upon widget use.

**Comment by Joshix-1** [comment]
I'm stupid, you having the LICENSE file is already enough. It's already displayed in the licenses page
