### ISSUE TITLE
Having trouble using a custom shape (ImageShape)

### ISSUE THREAD

**Issue by orkun1675** [tguerin/newton#20]
Great package, thank you for sharing!

I'm guessing because of these lines: https://github.com/tguerin/newton/blob/main/lib/src/particles/shape.dart#L93-L94

The image size is hardcoded to be 500x500 and doesn't play well with other image sizes.

Would it be possible to address that?

**Comment by tguerin** [comment]
Thanks for the feedback, image width and height should be used here you're right. Will fix that.
