### ISSUE TITLE
Newton causes all child widgets to rebuild each frame

### ISSUE THREAD

**Issue by orkun1675** [tguerin/newton#22]
I'm using Bloc + Newton. Before wrapping my widgets with Newton my app would idle without drawin any frames. Now, Flutter is trying to push out 60 FPS even on a static page when no animation is running.

Observe Flutter Performance tool for FPS change.

I've downloaded Android Studio to use the widget rebuild tracker to verify this.

I'll try to put together a minimal app to demonstrate this. In the meantime attaching a screenshot below.

<img width="1161" alt="Screenshot 2023-12-08 at 3 18 42 AM" src="https://github.com/tguerin/newton/assets/2564599/c0230ca4-7c16-400e-81ca-9509f70a898e">

**Comment by tguerin** [comment]
Right there is a ticker that triggers a setState({}) and it's triggered even if there is no animation causing the extra rebuild.

**Comment by orkun1675** [comment]
Is this something that is easy to fix? Happy to take a look if you want.

**Comment by tguerin** [comment]
The fix was made to only rebuild if there is any effect active. Newton requires a rebuild if any effect is active. To avoid having your child rebuild every frame, either declare it as `const` (if feasible) or move it to a stack, for example, so that only Newton performs the rebuild.
