### ISSUE TITLE
Stop animation progressively

### ISSUE THREAD

**Issue by angelorodem** [tguerin/newton#26]
Is it possible to control the emission "quantity"?

i mean, imagine the Rain effect, is it possible to slow down the emission and remove the effect? i have been trying to remove the effect but all particles just disappear without any smoothing, it would be nice to slow the effects will there is nothing in the screen before being able to remove.

**Comment by angelorodem** [comment]
i have tried to save the effect as a widget property, and calling its stop() and start() methods, but it seems to somehow speedup the effect before stopping it

**Comment by tguerin** [comment]
To the question can you control the quantity, the answer is yes, you can define a particle count. The effects will emit particle count particles according to the emission rate. For example, if you set 100 as particle count and 10 particles per second your effect will automatically stop after 10 seconds + (time of travelling for the las emitted particles to complete).

By slowing do you mean reducing the number of emitted particles when reaching the end?
