### ISSUE TITLE
Some ideas and possible PR previews

### ISSUE THREAD

**Issue by VonZen** [tguerin/newton#30]
About some optimizations & improvements:
1. Optimization: For ImageShape, what is needed in more cases is to retain the original image, such as an emoji, and only use the BlendMode mask mode in the case of a solid color image;
2. Improvement:

    1. Add Effect Instead of using SetState to refresh the Widget, use CustomPainter({Listenable? repaint}) comes with Listenable to handle additions or deletions, to notify Painter, to provide better performance, and to extend functionality;
      For example, NewtonPainter has an object inherited from Listenable that manages the Effect queue.
    2. Effect supports its own Shape, speed, direction and other attributes to cover the global configuration, which has provided greater flexibility, such as randomly ejecting a bunch of funny emoji, or dynamically changing the speed of Effect without fault

**Comment by tguerin** [comment]
First thank you for your feedback,

> Optimization: For ImageShape, what is needed in more cases is to retain the original image, such as an emoji, and only use the BlendMode mask mode in the case of a solid color image;

 you shouldn’t recreate the ImageShape once created you should reuse it or at least the image can be reused over shapes.

>Add Effect Instead of using SetState to refresh the Widget, use CustomPainter({Listenable? repaint}) comes with Listenable to handle additions or deletions, to notify Painter, to provide better performance, and to extend functionality;

I’m not sure how it will improve performance as the widget will still be rebuilt when the listenable will change. Could you provide some pseudo-code of your idea?

> Effect supports its own Shape, speed, direction and other attributes to cover the global configuration, which has provided greater flexibility, such as randomly ejecting a bunch of funny emoji, or dynamically changing the speed of Effect without fault

You should already be able to do that, existing effects (explode, rain) are provided mainly as examples. Feel free to create your own Effect and customize how the particles are instantiated. Regarding multiple shapes, it’s a good idea need to check how we could properly add it to the API.

**Comment by tguerin** [comment]
Fixed by #31
