### ISSUE TITLE
[idea] Add simpler effect interface to make implementing completly custom effects easier

### ISSUE THREAD

**Issue by Joshix-1** [tguerin/newton#34]
I'm not sure whether I really like this, but it's an idea I had.

The current Effect class has many things special to itself. A parent interface with less properties that should be required instead of Effect in most cases would make it easier to implement completly custom effects. EffectConfiguration has imho too many options that i don't need most of the time.

```dart
abstract interface class IEffect<T extends AnimatedParticle> {
  /// Root effect that triggered this effect
  Effect get rootEffect;
  /// Should the effect be played in foreground?
  bool get foreground;

  /// Current state of the effect
  EffectState get state;

  bool get addedAtRuntime;
  set addedAtRuntime(bool value);

  /// Immutable List of active particles managed by the effect.
  Iterable<AnimatedParticle> get activeParticles;

  /// Advances the effect animation based on the elapsed time in milliseconds.
  /// This method is automatically called to update the particle animation.
  void forward(int elapsedMillis);

  set postEffectCallback(ValueChanged<Effect>? effect);

  /// Callback to be notified when state has changed
  set stateChangeCallback(void Function(Effect, EffectState)? value);

  /// Size of the animation surface.
  set surfaceSize(Size value);

   /// Starts the effect emission, allowing particles to be emitted.
  void start();

  /// Stops the effect emission, optionally cancelling all active particles.
  void stop({bool cancel = false});

  /// Kills the effect, stopping all particle emission and removing active particles.
  void kill();
}
```

**Comment by tguerin** [comment]
Not sure to get the point, right now the only thing to implement for effect is `instantiateParticle`, other methods are here to let people have the possibility to override them if needed. Do you have a sample code to show what's bothering you?

**Comment by Joshix-1** [comment]
I'm not sure myself. Yes right now one only has to override instantiateParticle, that would still be the case when extending Effect.

I'm thinking about creating effects that can't be represented by EffectConfiguration. The current Effect class always requires EffectConfiguration, I don't really like that. The interface would allow creating another Effect class that doesn't use EffectConfiguration.

**Comment by tguerin** [comment]
The EffectConfiguration is here to help you modulate part of the animation, but an effect is not forced to take into account all the parameters of an EffectConfiguration. That's why all the properties have default values. I love practical example so if you have an effect in mind let's try to implement it and see how we could improve the API. I'm eager to see what you are cooking :D

**Comment by tguerin** [comment]
There is no reason, effect only deals with AnimatedParticles and doesn‘t car about subtypes

**Comment by tguerin** [comment]
This one can be closed as the new implementation coming with physics doesn’t require creating custom effects anymore. Everything can be achieved through configuration.
